/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fenetre;

import code.Duel;
import code.Joueur;
import code.LecteurScore;
import code.Partie;
import java.io.File;
import javax.swing.JOptionPane;

/**
 * @author team : ALICHERIF Elhaous, MOUHAMAD Imame & NGUYEN Quang Minh
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnSolo = new javax.swing.JButton();
        btnDuel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JMenuBar monMenu = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnRecord = new javax.swing.JMenuItem();
        ApropoDe = new javax.swing.JMenuItem();
        mnQuitter = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSolo.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        btnSolo.setForeground(new java.awt.Color(0, 102, 102));
        btnSolo.setText("Mode Solo");
        btnSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoloActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 275, -1, -1));

        btnDuel.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        btnDuel.setForeground(new java.awt.Color(0, 102, 102));
        btnDuel.setText("Mode Duel");
        btnDuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/acc.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        jMenu4.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Règles");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        mnRecord.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnRecord.setLabel("Record");
        mnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecordActionPerformed(evt);
            }
        });
        jMenu4.add(mnRecord);

        ApropoDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        ApropoDe.setText("A propos de...");
        ApropoDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApropoDeActionPerformed(evt);
            }
        });
        jMenu4.add(ApropoDe);

        mnQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnQuitter.setText("Quitter");
        mnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuitterActionPerformed(evt);
            }
        });
        jMenu4.add(mnQuitter);

        monMenu.add(jMenu4);

        setJMenuBar(monMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuitterActionPerformed
       System.exit(0);
    }//GEN-LAST:event_mnQuitterActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Aide a=new Aide();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ApropoDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApropoDeActionPerformed
        // TODO add your handling code here:
        Apropos ap=new Apropos();
        ap.setVisible(true);
    }//GEN-LAST:event_ApropoDeActionPerformed

    private void btnSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoloActionPerformed
        // nouvelle partie
    int n=0;//niveau    
    JOptionPane jop = new JOptionPane(), jop2 = new JOptionPane();
    String nom = jop.showInputDialog(null, "Veuillez entrer votre pseudo !", "Bonjour...?", JOptionPane.QUESTION_MESSAGE);
     String[] difficulte = {"Facile", "Moyen", "Difficile"};
    String diff=(String)jop2.showInputDialog(null, "Bienvenue " + nom, "Choissez un niveau",JOptionPane.QUESTION_MESSAGE,null,difficulte,difficulte[2]);
      switch(diff){
          case "Facile": n=4;break;
          case "Moyen": n=5;break;
          case "Difficile": n=6;break;    
      }  
      
      code.Partie p=new Partie(n,new Joueur(nom),1);
      switch(n){
          case 4: new PlateauJeu(p).setVisible(true);this.dispose();break;
          case 5: new PlateauJeuLvl2(p).setVisible(true);this.dispose();break;
          case 6: new PlateauJeuLvl3(p).setVisible(true);this.dispose();break;    
      }
    }//GEN-LAST:event_btnSoloActionPerformed

    private void btnDuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuelActionPerformed
        int n=0;//niveau    
    JOptionPane jop = new JOptionPane(), jop2 = new JOptionPane();
    String[] difficulte = {"Facile", "Moyen", "Difficile"};
    String diff=(String)jop2.showInputDialog(null, "Bienvenue ", "Choissez un niveau",JOptionPane.QUESTION_MESSAGE,null,difficulte,difficulte[2]);
      switch(diff){
          case "Facile": n=4;break;
          case "Moyen": n=5;break;
          case "Difficile": n=6;break;    
      }  
    String nom = jop.showInputDialog(null, "Veuillez entrer votre pseudo Joueur 1!", "Bonjour...?", JOptionPane.QUESTION_MESSAGE);
    String nom2 = jop.showInputDialog(null, "Veuillez entrer votre pseudo Joueur 2!", "Bonjour...?", JOptionPane.QUESTION_MESSAGE);
     
     
       /*Duel d=new Duel(new Joueur(nom),new Joueur(nom2), n);
       d.jouer();*/
    SelecteurCouleur s=new SelecteurCouleur(n,new Joueur(nom),new Joueur (nom2),1);
    s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDuelActionPerformed

    private void mnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecordActionPerformed
      Podium p=new Podium();
      p.setVisible(true);
    }//GEN-LAST:event_mnRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ApropoDe;
    private javax.swing.JButton btnDuel;
    private javax.swing.JButton btnSolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnQuitter;
    private javax.swing.JMenuItem mnRecord;
    // End of variables declaration//GEN-END:variables
}
