/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetre;

import code.Combinaison;
import code.EcrivainScore;
import code.LecteurScore;
import code.Partie;
import java.beans.EventHandler;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 * @author team : ALICHERIF Elhaous, MOUHAMAD Imame & NGUYEN Quang Minh
 */
public class PlateauJeuLvl3 extends javax.swing.JFrame {
    
    code.Partie p;
    int l;
    int round;
    int compteur;
    ArrayList<JLabel> ensLabel = new ArrayList<>();
    ArrayList<String> colors = new ArrayList<>();
    
    /** Creates new form PlateauJeuLvl3 */
    public PlateauJeuLvl3() {
        initComponents();
    }
    
        public PlateauJeuLvl3(code.Partie n) {
        initComponents();
        p = new Partie(0, null,0);
        p = n;
        l = 0;
        round=1;
        compteur = l;
        p.incEssai();
        ensLabel.add(b11);
        ensLabel.add(b12);
        ensLabel.add(b13);
        ensLabel.add(b14);
        ensLabel.add(b15);
        ensLabel.add(b16);
        ensLabel.add(b21);
        ensLabel.add(b22);
        ensLabel.add(b23);
        ensLabel.add(b24);
        ensLabel.add(b25);
        ensLabel.add(b26);
        ensLabel.add(b31);
        ensLabel.add(b32);
        ensLabel.add(b33);
        ensLabel.add(b34);
        ensLabel.add(b35);
        ensLabel.add(b36);
        ensLabel.add(b41);
        ensLabel.add(b42);
        ensLabel.add(b43);
        ensLabel.add(b44);
        ensLabel.add(b45);
        ensLabel.add(b46);
        ensLabel.add(b51);
        ensLabel.add(b52);
        ensLabel.add(b53);
        ensLabel.add(b54);
        ensLabel.add(b55);
        ensLabel.add(b56);
        ensLabel.add(b61);
        ensLabel.add(b62);
        ensLabel.add(b63);
        ensLabel.add(b64);
        ensLabel.add(b65);
        ensLabel.add(b66);
        ensLabel.add(b71);
        ensLabel.add(b72);
        ensLabel.add(b73);
        ensLabel.add(b74);
        ensLabel.add(b75);
        ensLabel.add(b76);
        ensLabel.add(b81);
        ensLabel.add(b82);
        ensLabel.add(b83);
        ensLabel.add(b84);
        ensLabel.add(b85);
        ensLabel.add(b86);
        ensLabel.add(b91);
        ensLabel.add(b92);
        ensLabel.add(b93);
        ensLabel.add(b94);
        ensLabel.add(b95);
        ensLabel.add(b96);
        ensLabel.add(b101);
        ensLabel.add(b102);
        ensLabel.add(b103);
        ensLabel.add(b104);
        ensLabel.add(b105);
        ensLabel.add(b106);
    p.getCode().afficher();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res10 = new javax.swing.JLabel();
        res9 = new javax.swing.JLabel();
        res8 = new javax.swing.JLabel();
        res7 = new javax.swing.JLabel();
        res6 = new javax.swing.JLabel();
        res5 = new javax.swing.JLabel();
        res4 = new javax.swing.JLabel();
        res3 = new javax.swing.JLabel();
        res2 = new javax.swing.JLabel();
        res1 = new javax.swing.JLabel();
        case1 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        b16 = new javax.swing.JLabel();
        case2 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        b23 = new javax.swing.JLabel();
        b24 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        b26 = new javax.swing.JLabel();
        case3 = new javax.swing.JLabel();
        b31 = new javax.swing.JLabel();
        b32 = new javax.swing.JLabel();
        b33 = new javax.swing.JLabel();
        b34 = new javax.swing.JLabel();
        b35 = new javax.swing.JLabel();
        b36 = new javax.swing.JLabel();
        case4 = new javax.swing.JLabel();
        b41 = new javax.swing.JLabel();
        b42 = new javax.swing.JLabel();
        b43 = new javax.swing.JLabel();
        b44 = new javax.swing.JLabel();
        b45 = new javax.swing.JLabel();
        b46 = new javax.swing.JLabel();
        case5 = new javax.swing.JLabel();
        b51 = new javax.swing.JLabel();
        b52 = new javax.swing.JLabel();
        b53 = new javax.swing.JLabel();
        b54 = new javax.swing.JLabel();
        b55 = new javax.swing.JLabel();
        b56 = new javax.swing.JLabel();
        case6 = new javax.swing.JLabel();
        b61 = new javax.swing.JLabel();
        b62 = new javax.swing.JLabel();
        b63 = new javax.swing.JLabel();
        b64 = new javax.swing.JLabel();
        b65 = new javax.swing.JLabel();
        b66 = new javax.swing.JLabel();
        case7 = new javax.swing.JLabel();
        b71 = new javax.swing.JLabel();
        b72 = new javax.swing.JLabel();
        b73 = new javax.swing.JLabel();
        b74 = new javax.swing.JLabel();
        b75 = new javax.swing.JLabel();
        b76 = new javax.swing.JLabel();
        case8 = new javax.swing.JLabel();
        b81 = new javax.swing.JLabel();
        b82 = new javax.swing.JLabel();
        b83 = new javax.swing.JLabel();
        b84 = new javax.swing.JLabel();
        b85 = new javax.swing.JLabel();
        b86 = new javax.swing.JLabel();
        case9 = new javax.swing.JLabel();
        b91 = new javax.swing.JLabel();
        b92 = new javax.swing.JLabel();
        b93 = new javax.swing.JLabel();
        b94 = new javax.swing.JLabel();
        b95 = new javax.swing.JLabel();
        b96 = new javax.swing.JLabel();
        case10 = new javax.swing.JLabel();
        b101 = new javax.swing.JLabel();
        b102 = new javax.swing.JLabel();
        b103 = new javax.swing.JLabel();
        b104 = new javax.swing.JLabel();
        b105 = new javax.swing.JLabel();
        b106 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Accueil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jaune = new javax.swing.JLabel();
        verte = new javax.swing.JLabel();
        bleue = new javax.swing.JLabel();
        blanc = new javax.swing.JLabel();
        marron = new javax.swing.JLabel();
        noir = new javax.swing.JLabel();
        orange = new javax.swing.JLabel();
        violette = new javax.swing.JLabel();
        rose = new javax.swing.JLabel();
        rouge = new javax.swing.JLabel();
        Qui = new javax.swing.JButton();
        fondPalette = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 695));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        res10.setBackground(new java.awt.Color(0, 0, 0));
        res10.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res10.setForeground(new java.awt.Color(-1,true));
        res10.setText("* * * * * *");
        res10.setOpaque(true);
        getContentPane().add(res10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 135, -1, 30));

        res9.setBackground(new java.awt.Color(0, 0, 0));
        res9.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res9.setForeground(new java.awt.Color(-1,true));
        res9.setText("* * * * * *");
        res9.setOpaque(true);
        getContentPane().add(res9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 185, -1, 30));

        res8.setBackground(new java.awt.Color(0, 0, 0));
        res8.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res8.setForeground(new java.awt.Color(-1,true));
        res8.setText("* * * * * *");
        res8.setOpaque(true);
        getContentPane().add(res8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 235, -1, 30));

        res7.setBackground(new java.awt.Color(0, 0, 0));
        res7.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res7.setForeground(new java.awt.Color(-1,true));
        res7.setText("* * * * * *");
        res7.setOpaque(true);
        getContentPane().add(res7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 285, -1, 30));

        res6.setBackground(new java.awt.Color(0, 0, 0));
        res6.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res6.setForeground(new java.awt.Color(-1,true));
        res6.setText("* * * * * *");
        res6.setToolTipText("");
        res6.setOpaque(true);
        getContentPane().add(res6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 335, -1, 30));

        res5.setBackground(new java.awt.Color(0, 0, 0));
        res5.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res5.setForeground(new java.awt.Color(-1,true));
        res5.setText("* * * * * *");
        res5.setOpaque(true);
        getContentPane().add(res5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 385, -1, 30));

        res4.setBackground(new java.awt.Color(0, 0, 0));
        res4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res4.setForeground(new java.awt.Color(-1,true));
        res4.setText("* * * * * *");
        res4.setName(""); // NOI18N
        res4.setOpaque(true);
        getContentPane().add(res4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 435, -1, 30));

        res3.setBackground(new java.awt.Color(0, 0, 0));
        res3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res3.setForeground(new java.awt.Color(-1,true));
        res3.setText("* * * * * *");
        res3.setOpaque(true);
        getContentPane().add(res3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 485, -1, 30));

        res2.setBackground(new java.awt.Color(0, 0, 0));
        res2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res2.setForeground(new java.awt.Color(-1,true));
        res2.setText("* * * * * *");
        res2.setOpaque(true);
        getContentPane().add(res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 535, -1, 30));

        res1.setBackground(new java.awt.Color(0, 0, 0));
        res1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        res1.setForeground(new java.awt.Color(-1,true));
        res1.setText("* * * * * *");
        res1.setOpaque(true);
        getContentPane().add(res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 585, -1, 30));

        case1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 575, -1, -1));

        b11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setToolTipText("");
        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b11MouseClicked(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 581, 34, 36));

        b12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setToolTipText("");
        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b12MouseClicked(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 581, 34, 36));

        b13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b13MouseClicked(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 581, 34, 36));

        b14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b14.setToolTipText("");
        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b14MouseClicked(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 581, 34, 36));

        b15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b15MouseClicked(evt);
            }
        });
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 581, 34, 36));

        b16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b16MouseClicked(evt);
            }
        });
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 581, 34, 36));

        case2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 525, -1, -1));

        b21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b21MouseClicked(evt);
            }
        });
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 531, 34, 36));

        b22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b22.setToolTipText("");
        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b22MouseClicked(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 531, 34, 36));

        b23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b23MouseClicked(evt);
            }
        });
        getContentPane().add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 531, 34, 36));

        b24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b24MouseClicked(evt);
            }
        });
        getContentPane().add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 531, 34, 36));

        b25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b25MouseClicked(evt);
            }
        });
        getContentPane().add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 531, 34, 35));

        b26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b26MouseClicked(evt);
            }
        });
        getContentPane().add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 531, 34, 36));

        case3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 475, -1, 50));

        b31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b31MouseClicked(evt);
            }
        });
        getContentPane().add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 481, 34, 36));

        b32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b32MouseClicked(evt);
            }
        });
        getContentPane().add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 481, 34, 36));

        b33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b33MouseClicked(evt);
            }
        });
        getContentPane().add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 481, 34, 36));

        b34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b34MouseClicked(evt);
            }
        });
        getContentPane().add(b34, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 481, 34, 36));

        b35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b35MouseClicked(evt);
            }
        });
        getContentPane().add(b35, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 481, 34, 36));

        b36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b36MouseClicked(evt);
            }
        });
        getContentPane().add(b36, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 481, 34, 36));

        case4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 425, -1, -1));

        b41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b41MouseClicked(evt);
            }
        });
        getContentPane().add(b41, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 431, 34, 36));

        b42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b42MouseClicked(evt);
            }
        });
        getContentPane().add(b42, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 431, 34, 36));

        b43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b43MouseClicked(evt);
            }
        });
        getContentPane().add(b43, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 431, 34, 36));

        b44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b44MouseClicked(evt);
            }
        });
        getContentPane().add(b44, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 431, 34, 36));

        b45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b45MouseClicked(evt);
            }
        });
        getContentPane().add(b45, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 431, 34, 36));

        b46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b46MouseClicked(evt);
            }
        });
        getContentPane().add(b46, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 431, 34, 36));

        case5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 375, -1, -1));

        b51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b51MouseClicked(evt);
            }
        });
        getContentPane().add(b51, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 381, 34, 36));

        b52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b52MouseClicked(evt);
            }
        });
        getContentPane().add(b52, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 381, 34, 36));

        b53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b53MouseClicked(evt);
            }
        });
        getContentPane().add(b53, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 381, 34, 36));

        b54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b54.setToolTipText("");
        b54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b54MouseClicked(evt);
            }
        });
        getContentPane().add(b54, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 381, 34, 36));

        b55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b55MouseClicked(evt);
            }
        });
        getContentPane().add(b55, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 381, 34, 36));

        b56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b56MouseClicked(evt);
            }
        });
        getContentPane().add(b56, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 381, 34, 36));

        case6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, -1, -1));

        b61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b61MouseClicked(evt);
            }
        });
        getContentPane().add(b61, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 331, 34, 36));

        b62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b62MouseClicked(evt);
            }
        });
        getContentPane().add(b62, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 331, 34, 36));

        b63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b63MouseClicked(evt);
            }
        });
        getContentPane().add(b63, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 331, 34, 36));

        b64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b64.setToolTipText("");
        b64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b64MouseClicked(evt);
            }
        });
        getContentPane().add(b64, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 331, 34, 36));

        b65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b65MouseClicked(evt);
            }
        });
        getContentPane().add(b65, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 331, 34, 36));

        b66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b66MouseClicked(evt);
            }
        });
        getContentPane().add(b66, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 331, 34, 36));

        case7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 275, -1, -1));

        b71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b71MouseClicked(evt);
            }
        });
        getContentPane().add(b71, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 281, 34, 36));

        b72.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b72MouseClicked(evt);
            }
        });
        getContentPane().add(b72, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 281, 34, 36));

        b73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b73MouseClicked(evt);
            }
        });
        getContentPane().add(b73, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 281, 34, 36));

        b74.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b74MouseClicked(evt);
            }
        });
        getContentPane().add(b74, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 281, 34, 36));

        b75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b75.setToolTipText("");
        b75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b75MouseClicked(evt);
            }
        });
        getContentPane().add(b75, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 281, 34, 36));

        b76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b76MouseClicked(evt);
            }
        });
        getContentPane().add(b76, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 281, 34, 36));

        case8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, -1, -1));

        b81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b81.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b81MouseClicked(evt);
            }
        });
        getContentPane().add(b81, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 231, 34, 36));

        b82.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b82MouseClicked(evt);
            }
        });
        getContentPane().add(b82, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 231, 34, 36));

        b83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b83MouseClicked(evt);
            }
        });
        getContentPane().add(b83, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 231, 34, 36));

        b84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b84MouseClicked(evt);
            }
        });
        getContentPane().add(b84, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 231, 34, 36));

        b85.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b85MouseClicked(evt);
            }
        });
        getContentPane().add(b85, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 231, 34, 36));

        b86.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b86.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b86MouseClicked(evt);
            }
        });
        getContentPane().add(b86, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 231, 34, 36));

        case9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 175, -1, -1));

        b91.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b91MouseClicked(evt);
            }
        });
        getContentPane().add(b91, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 181, 34, 36));

        b92.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b92MouseClicked(evt);
            }
        });
        getContentPane().add(b92, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 181, 34, 36));

        b93.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b93.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b93MouseClicked(evt);
            }
        });
        getContentPane().add(b93, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 181, 34, 36));

        b94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b94.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b94MouseClicked(evt);
            }
        });
        getContentPane().add(b94, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 181, 34, 36));

        b95.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b95MouseClicked(evt);
            }
        });
        getContentPane().add(b95, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 181, 34, 36));

        b96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b96.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b96MouseClicked(evt);
            }
        });
        getContentPane().add(b96, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 181, 34, 36));

        case10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case3tr.png"))); // NOI18N
        getContentPane().add(case10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, -1, -1));

        b101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b101MouseClicked(evt);
            }
        });
        getContentPane().add(b101, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 131, 34, 36));

        b102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b102MouseClicked(evt);
            }
        });
        getContentPane().add(b102, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 131, 34, 36));

        b103.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b103MouseClicked(evt);
            }
        });
        getContentPane().add(b103, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 131, 34, 36));

        b104.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b104MouseClicked(evt);
            }
        });
        getContentPane().add(b104, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 131, 34, 36));

        b105.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b105MouseClicked(evt);
            }
        });
        getContentPane().add(b105, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 131, 34, 36));

        b106.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b106MouseClicked(evt);
            }
        });
        getContentPane().add(b106, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 131, 34, 36));

        Valider.setText("Valider");
        Valider.setToolTipText("");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 70, -1));

        Accueil.setText("Accueil");
        Accueil.setToolTipText("");
        Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilActionPerformed(evt);
            }
        });
        getContentPane().add(Accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("<html> <p>1 --> Bonne couleur mais mauvaise position   <p> <p> <p>2 --> Bonne couleur et bonne position  </html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 260, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Astuces :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/master_mind_logo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 15, 500, 70));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel6.setText("Palette de couleurs :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FOND JEU - Copie.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, 340, 550));

        jaune.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jaune.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jaune.jpg"))); // NOI18N
        jaune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jauneMouseClicked(evt);
            }
        });
        getContentPane().add(jaune, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 40, 50));

        verte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vert.jpg"))); // NOI18N
        verte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verteMouseClicked(evt);
            }
        });
        getContentPane().add(verte, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 50, 50));

        bleue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bleue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bleu.jpg"))); // NOI18N
        bleue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bleueMouseClicked(evt);
            }
        });
        getContentPane().add(bleue, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 50, 40));

        blanc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.jpg"))); // NOI18N
        blanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancMouseClicked(evt);
            }
        });
        getContentPane().add(blanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 50, 50));

        marron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/marron.jpg"))); // NOI18N
        marron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marronMouseClicked(evt);
            }
        });
        getContentPane().add(marron, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 40, 50));

        noir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/noir.jpg"))); // NOI18N
        noir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noirMouseClicked(evt);
            }
        });
        getContentPane().add(noir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, 60));

        orange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/orange.png"))); // NOI18N
        orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeMouseClicked(evt);
            }
        });
        getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 60, 50));

        violette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        violette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/violet.jpg"))); // NOI18N
        violette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                violetteMouseClicked(evt);
            }
        });
        getContentPane().add(violette, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 50, 40));

        rose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rose.jpg"))); // NOI18N
        rose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseMouseClicked(evt);
            }
        });
        getContentPane().add(rose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 60, 50));

        rouge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rouge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rouge.jpg"))); // NOI18N
        rouge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rougeMouseClicked(evt);
            }
        });
        getContentPane().add(rouge, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 40, 50));

        Qui.setText("Qui joue ?");
        Qui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuiActionPerformed(evt);
            }
        });
        getContentPane().add(Qui, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        fondPalette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondPalette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.png"))); // NOI18N
        fondPalette.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fondPalette, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 220, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fond-gris-galyoneo.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void b11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseClicked
         if(l<7){
             if(b11.getIcon()!=null){
                b11.setIcon(null);
                b12.setIcon(null);
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                b16.setIcon(null);
                l=0;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b11MouseClicked
private void b21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b21MouseClicked
        if(l<13){
             if(b21.getIcon()!=null){
                b21.setText(null);
                b22.setText(null);
                b23.setText(null);
                b24.setText(null);
                b25.setText(null);
                b26.setText(null);
                l=6;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b21MouseClicked
private void b31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b31MouseClicked
        if(l<19){
             if(b31.getIcon()!=null){
                b31.setIcon(null);
                b32.setIcon(null);
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                b36.setIcon(null);
                l=12;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b31MouseClicked
private void b41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b41MouseClicked
        if(l<25){
             if(b41.getIcon()!=null){
                b41.setIcon(null);
                b42.setIcon(null);
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                b46.setIcon(null);
                l=18;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b41MouseClicked
private void b51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b51MouseClicked
        if(l<31){
             if(b51.getIcon()!=null){
                b51.setIcon(null);
                b52.setIcon(null);
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                b56.setIcon(null);
                l=24;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b51MouseClicked
private void b61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b61MouseClicked
        if(l<37){
             if(b61.getIcon()!=null){
                b61.setIcon(null);
                b62.setIcon(null);
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                b66.setIcon(null);
                l=30;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b61MouseClicked
private void b71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b71MouseClicked
        if(l<43){
             if(b71.getIcon()!=null){
                b71.setIcon(null);
                b72.setIcon(null);
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                b76.setIcon(null);
                l=36;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b71MouseClicked
private void b81MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b81MouseClicked
        if(l<49){
             if(b81.getIcon()!=null){
                b81.setIcon(null);
                b82.setIcon(null);
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                b86.setIcon(null);
                l=42;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b81MouseClicked
private void b91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b91MouseClicked
        if(l<55){
             if(b91.getIcon()!=null){
                b91.setIcon(null);
                b92.setIcon(null);
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                b96.setIcon(null);
                l=48;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b91MouseClicked
private void b101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b101MouseClicked
        if(l<61){
             if(b101.getIcon()!=null){
                b101.setIcon(null);
                b102.setIcon(null);
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                b106.setIcon(null);
                l=54;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b101MouseClicked
private void b12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b12MouseClicked
        if(l<7){
             if(b12.getIcon()!=null){
                b12.setIcon(null);
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                b16.setIcon(null);
                l=1;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b12MouseClicked
private void b22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b22MouseClicked
        if(l<13){
             if(b22.getIcon()!=null){
                b22.setIcon(null);
                b23.setIcon(null);
                b24.setIcon(null);
                b25.setIcon(null);
                b26.setIcon(null);
                l=7;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b22MouseClicked
private void b32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b32MouseClicked
        if(l<19){
             if(b32.getIcon()!=null){
                b32.setIcon(null);
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                b36.setIcon(null);
                l=13;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b32MouseClicked
private void b42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b42MouseClicked
        if(l<25){
             if(b42.getIcon()!=null){
                b42.setIcon(null);
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                b46.setIcon(null);
                l=19;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b42MouseClicked
private void b52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b52MouseClicked
        if(l<31){
             if(b52.getIcon()!=null){
                b52.setIcon(null);
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                b56.setIcon(null);
                l=25;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b52MouseClicked
private void b62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b62MouseClicked
        if(l<37){
             if(b62.getIcon()!=null){
                b62.setIcon(null);
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                b66.setIcon(null);
                l=31;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b62MouseClicked
private void b72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b72MouseClicked
        if(l<43){
             if(b72.getIcon()!=null){
                b72.setIcon(null);
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                b76.setIcon(null);
                l=37;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b72MouseClicked
private void b82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b82MouseClicked
        if(l<49){
             if(b82.getIcon()!=null){
                b82.setIcon(null);
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                b86.setIcon(null);
                l=43;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b82MouseClicked
private void b92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b92MouseClicked
        if(l<55){
             if(b92.getIcon()!=null){
                b92.setIcon(null);
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                b96.setIcon(null);
                l=49;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b92MouseClicked
private void b102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b102MouseClicked
        if(l<61){
             if(b102.getIcon()!=null){
                b102.setIcon(null);
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                b106.setIcon(null);
                l=55;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b102MouseClicked
private void b13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseClicked
        if(l<7){
             if(b13.getIcon()!=null){
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                b16.setIcon(null);
                l=2;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b13MouseClicked
private void b23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b23MouseClicked
        if(l<13){
             if(b23.getIcon()!=null){
                b23.setIcon(null);
                b24.setIcon(null);
                b25.setIcon(null);
                b26.setIcon(null);
                l=8;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b23MouseClicked
private void b33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b33MouseClicked
        if(l<19){
             if(b33.getIcon()!=null){
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                b36.setIcon(null);
                l=14;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b33MouseClicked
private void b43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b43MouseClicked
        if(l<25){
             if(b43.getIcon()!=null){
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                b46.setIcon(null);
                l=20;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b43MouseClicked
private void b53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b53MouseClicked
        if(l<31){
             if(b53.getIcon()!=null){
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                b56.setIcon(null);
                l=26;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b53MouseClicked
private void b63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b63MouseClicked
        if(l<37){
             if(b63.getIcon()!=null){
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                b66.setIcon(null);
                l=32;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b63MouseClicked
private void b73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b73MouseClicked
        if(l<43){
             if(b73.getIcon()!=null){
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                b76.setIcon(null);
                l=38;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b73MouseClicked
private void b83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b83MouseClicked
        if(l<49){
             if(b83.getIcon()!=null){
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                b86.setIcon(null);
                l=44;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b83MouseClicked
private void b93MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b93MouseClicked
        if(l<55){
             if(b93.getIcon()!=null){
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                b96.setIcon(null);
                l=50;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b93MouseClicked
private void b103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b103MouseClicked
        if(l<61){
             if(b103.getIcon()!=null){
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                b106.setIcon(null);
                l=56;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b103MouseClicked
private void b14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b14MouseClicked
        if(l<7){
             if(b14.getIcon()!=null){
                b14.setIcon(null);
                b15.setIcon(null);
                b16.setIcon(null);
                l=3;
                compteur = 3;
                colors=maj_colors(colors,l);
                
            }
        }
}//GEN-LAST:event_b14MouseClicked
private void b24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b24MouseClicked
        if(l<13){
             if(b24.getIcon()!=null){
                b24.setIcon(null);
                b25.setIcon(null);
                b26.setIcon(null);
                l=9;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b24MouseClicked
private void b34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b34MouseClicked
        if(l<19){
             if(b34.getIcon()!=null){
                b34.setIcon(null);
                b35.setIcon(null);
                b36.setIcon(null);
                l=15;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b34MouseClicked
private void b44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b44MouseClicked
        if(l<25){
             if(b44.getIcon()!=null){
                b44.setIcon(null);
                b45.setIcon(null);
                b46.setIcon(null);
                l=21;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b44MouseClicked
private void b54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b54MouseClicked
        if(l<31){
             if(b54.getIcon()!=null){
                b54.setIcon(null);
                b55.setIcon(null);
                b56.setIcon(null);
                l=27;
                compteur = 3;
                colors=maj_colors(colors,l);
             }
        }
}//GEN-LAST:event_b54MouseClicked
private void b64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b64MouseClicked
        if(l<37){
             if(b64.getIcon()!=null){
                b64.setIcon(null);
                b65.setIcon(null);
                b66.setIcon(null);
                l=33;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b64MouseClicked
private void b74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b74MouseClicked
        if(l<43){
             if(b74.getIcon()!=null){
                b74.setIcon(null);
                b75.setIcon(null);
                b76.setIcon(null);
                l=39;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b74MouseClicked
private void b84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b84MouseClicked
        if(l<49){
             if(b84.getIcon()!=null){
                b84.setIcon(null);
                b85.setIcon(null);
                b86.setIcon(null);
                l=45;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b84MouseClicked
private void b94MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b94MouseClicked
        if(l<55){
             if(b94.getIcon()!=null){
                b94.setIcon(null);
                b95.setIcon(null);
                b96.setIcon(null);
                l=51;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b94MouseClicked
private void b104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b104MouseClicked
        if(l<61){
             if(b104.getIcon()!=null){
                b104.setIcon(null);
                b105.setIcon(null);
                b106.setIcon(null);
                l=57;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b104MouseClicked
private void b15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b15MouseClicked
        if(l<7){
            if(b15.getIcon()!=null){
                b15.setIcon(null);
                b16.setIcon(null);
                l=4;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b15MouseClicked
private void b25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b25MouseClicked
        if(l<13){
             if(b25.getIcon()!=null){
                b25.setIcon(null);
                b26.setIcon(null);
                l=10;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b25MouseClicked
private void b35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b35MouseClicked
        if(l<19){
             if(b35.getIcon()!=null){
                b35.setIcon(null);
                b36.setIcon(null);
                l=16;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b35MouseClicked
private void b45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b45MouseClicked
        if(l<25){
             if(b45.getIcon()!=null){
                b45.setIcon(null);
                b46.setIcon(null);
                l=22;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b45MouseClicked
private void b55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b55MouseClicked
        if(l<31){
             if(b55.getIcon()!=null){
                b55.setIcon(null);
                b56.setIcon(null);
                l=28;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b55MouseClicked
private void b65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b65MouseClicked
        if(l<37){
             if(b55.getIcon()!=null){
                b65.setIcon(null);
                b66.setIcon(null);
                l=34;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b65MouseClicked
private void b75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b75MouseClicked
        if(l<43){
             if(b75.getIcon()!=null){
                b75.setIcon(null);
                b76.setIcon(null);
                l=40;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b75MouseClicked
private void b85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b85MouseClicked
        if(l<49){
             if(b85.getIcon()!=null){
                b85.setIcon(null);
                b86.setIcon(null);
                l=46;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b85MouseClicked
private void b95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b95MouseClicked
        if(l<55){
             if(b95.getIcon()!=null){
                b95.setIcon(null);
                b96.setIcon(null);
                l=52;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b95MouseClicked
private void b105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b105MouseClicked
        if(l<61){
             if(b105.getIcon()!=null){
                b105.setIcon(null);
                b106.setIcon(null);
                l=58;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b105MouseClicked
private void b16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b16MouseClicked
        if(l<7){
             if(b16.getIcon()!=null){
                b16.setIcon(null);
                l=5;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b16MouseClicked
private void b26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b26MouseClicked
        if(l<13){
             if(b26.getIcon()!=null){
                b26.setIcon(null);
                l=11;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b26MouseClicked
private void b36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b36MouseClicked
        if(l<19){
             if(b36.getIcon()!=null){
                b36.setIcon(null);
                l=17;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b36MouseClicked
private void b46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b46MouseClicked
        if(l<25){
            if(b46.getIcon()!=null){
                b46.setIcon(null);
                l=23;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b46MouseClicked
private void b56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b56MouseClicked
        if(l<31){
             if(b56.getIcon()!=null){
                b56.setIcon(null);
                l=29;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b56MouseClicked
private void b66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b66MouseClicked
        if(l<37){
             if(b66.getIcon()!=null){
                b66.setIcon(null);
                l=35;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b66MouseClicked
private void b76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b76MouseClicked
        if(l<43){
             if(b76.getIcon()!=null){
                b76.setIcon(null);
                l=41;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b76MouseClicked
private void b86MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b86MouseClicked
        if(l<49){
             if(b86.getIcon()!=null){
                b86.setIcon(null);
                l=47;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b86MouseClicked
private void b96MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b96MouseClicked
        if(l<55){
             if(b96.getIcon()!=null){
                b96.setIcon(null);
                l=53;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b96MouseClicked
private void b106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b106MouseClicked
        if(l<61){
             if(b106.getIcon()!=null){
                b106.setIcon(null);
                l=59;
                compteur = 5;
                colors=maj_colors(colors,l);
            }
        }
}//GEN-LAST:event_b106MouseClicked
    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        if(compteur==6){
            noir.setVisible(true);
            blanc.setVisible(true);
            rouge.setVisible(true);
            bleue.setVisible(true);
            rose.setVisible(true);
            verte.setVisible(true);
            violette.setVisible(true);
            orange.setVisible(true);
            marron.setVisible(true);
            jaune.setVisible(true);
      
            switch(p.getEssai()){
                case 1: Combinaison c=new Combinaison();
                    for(int i=0;i<6;i++){
                        c.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c);
                    p.verifier(c);
                    afficherResultat(res1, c);
                    checkFin();
                    p.incEssai();
                    break;
                case 2: Combinaison c1=new Combinaison();
                    for(int i=6;i<12;i++){
                        c1.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c1);
                    p.verifier(c1);
                    afficherResultat(res2, c1);
                    checkFin();
                    p.incEssai();
                    break;
                case 3: Combinaison c2=new Combinaison();
                    for(int i=12;i<18;i++){
                        c2.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c2);
                    p.verifier(c2);
                    afficherResultat(res3, c2);
                    checkFin();
                    p.incEssai();
                    break; 
                case 4: Combinaison c3=new Combinaison();
                    for(int i=18;i<24;i++){
                        c3.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c3);
                    p.verifier(c3);
                    afficherResultat(res4, c3);
                    checkFin();
                    p.incEssai();
                    break;
                case 5: Combinaison c4=new Combinaison();
                    for(int i=24;i<30;i++){
                        c4.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c4);
                    p.verifier(c4);
                    afficherResultat(res5, c4);
                    checkFin();
                    p.incEssai();
                    break; 
                case 6: Combinaison c5=new Combinaison();
                    for(int i=30;i<36;i++){
                        c5.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c5);
                    p.verifier(c5);
                    afficherResultat(res6, c5);
                    checkFin();
                    p.incEssai();
                    break;
                case 7: Combinaison c6=new Combinaison();
                    for(int i=36;i<42;i++){
                        c6.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c6);
                    p.verifier(c6);
                    afficherResultat(res7, c6);
                    checkFin();
                    p.incEssai();
                    break; 
                case 8: Combinaison c7=new Combinaison();
                    for(int i=42;i<48;i++){
                        c7.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c7);
                    p.verifier(c7);
                    afficherResultat(res8, c7);
                    checkFin();
                    p.incEssai();
                    break;
                case 9: Combinaison c8=new Combinaison();
                    for(int i=48;i<54;i++){
                        c8.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c8);
                    p.verifier(c8);
                    afficherResultat(res9, c8);
                    checkFin();
                    p.incEssai();
                    break;
                case 10: Combinaison c9=new Combinaison();
                    for(int i=54;i<60;i++){
                        c9.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c9);
                    p.verifier(c9);
                    afficherResultat(res10, c9);
                    checkFin();
                    p.incEssai();
                    break;
            } 
            compteur = 0;
        }                                            
        else{
            new JOptionPane().showMessageDialog(null,"Vous devez choisir 6 couleurs","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    public ArrayList<String> maj_colors(ArrayList<String> c, int l){
        ArrayList<String> res=new ArrayList<>();
        int i;
        for(i=0; i<l; i++){
            res.add(c.get(i));
        }
        return res;
    }
    
    private void jauneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jauneMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jaune.jpg")));
            colors.add("J");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jauneMouseClicked
    private void verteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verteMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vert.jpg")));
            colors.add("G");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verteMouseClicked
    private void orangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/orange.png")));
            colors.add("O");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orangeMouseClicked
    private void bleueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bleueMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bleu.jpg")));
            colors.add("B");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bleueMouseClicked
    private void blancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.jpg")));
            colors.add("W");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_blancMouseClicked
    private void violetteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_violetteMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/violet.jpg")));
            colors.add("V");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_violetteMouseClicked
    private void noirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noirMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/noir.jpg")));
            colors.add("N");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_noirMouseClicked
    private void roseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rose.jpg")));
            colors.add("P");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_roseMouseClicked
    private void marronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marronMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/marron.jpg")));
            colors.add("M");l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_marronMouseClicked
    private void rougeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rougeMouseClicked
        if(compteur != 6  ){
            ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rouge.jpg")));
            colors.add("R");
            l++;
            compteur ++;
        }
        else {
            new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rougeMouseClicked

    private void AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilActionPerformed
        Acceuil a=new Acceuil();
                a.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_AccueilActionPerformed

    private void QuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuiActionPerformed
         new JOptionPane().showMessageDialog(null, "C'est le tour de "+p.getActif().getPseudo()+" jouer!","Joueur Actif",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_QuiActionPerformed

 
 public void checkFinDuel(){
        if(p.getActif().getEssai()==100){
            if(p.getJoueur().getRecord()>p.getJoueur2().getRecord())
            { new JOptionPane().showMessageDialog(null, "Désolé "+p.getJoueur2().getPseudo()+"!!!\n vous avez perdu","Fin de partie",JOptionPane.INFORMATION_MESSAGE);
              Acceuil a=new Acceuil();
            this.dispose();
            }
            else{
              new JOptionPane().showMessageDialog(null, "Désolé "+p.getJoueur().getPseudo()+"!!!\n vous avez perdu","Fin de partie",JOptionPane.INFORMATION_MESSAGE);
             Acceuil a=new Acceuil();
            this.dispose();
            }
          
    }}
     

 public void checkFin(){int r;
        if((p.getEssai()==10)||(p.getFin())){
            p.getActif().setEssai(p.getEssai());
            if(p.getFin()){
            javax.swing.JOptionPane.showMessageDialog(null,"Felicitation "+p.getActif().getPseudo()+" vous avez deviné le code secret" ,"Yatta",JOptionPane.INFORMATION_MESSAGE);
            new JOptionPane().showMessageDialog(null,"Le code était: "+p.getCode().afficher(),"Code",JOptionPane.INFORMATION_MESSAGE);
            p.getActif().setRecord(10-p.getEssai()+1);
            r= p.getActif().getRecord();
            if(p.getType()==1){
                Acceuil a=new Acceuil();
                a.setVisible(true);
                this.dispose();
                 }
                 else{
                checkFinDuel();
            /*    if(round%2==0)
                {*/
                 JOptionPane jop = new JOptionPane();
                 JOptionPane jop2 = new JOptionPane();
            
            jop2.showMessageDialog(null,"Nombre d'essai : "+p.getJoueur().getPseudo()+" : "+p.getJoueur().getEssai()+" \n"+p.getJoueur2().getPseudo()+" : "+p.getJoueur2().getEssai(),"Score",JOptionPane.INFORMATION_MESSAGE);
            round ++;
            jop.showMessageDialog(null, "Veuillez entrer le code "+p.getJoueur2().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
    
            s.setVisible(true);
            this.dispose();
            }
                  File f=new File("scoreDifficile.txt");
            if(f.exists()){
            code.LecteurScore l=new LecteurScore("scoreDifficile.txt");
            String score=l.lecture();
            System.out.println(score);
            int k=score.indexOf(":");
            String alire=score.substring(k+1, score.length());
            k=Integer.parseInt(alire);
            if(k<r){
               code.EcrivainScore e=new EcrivainScore(p.getActif().getPseudo(), 10-p.getEssai()+1,"scoreDifficile.txt");  
            }
            }
           else
            {
                code.EcrivainScore e=new EcrivainScore(p.getActif().getPseudo(), 10-p.getEssai()+1,"scoreDifficile.txt");
            }
            }     
        else{
            if(p.getEssai()==10){
                 if(p.getType()==1){
                     javax.swing.JOptionPane.showMessageDialog(null,"Désolé "+p.getActif().getPseudo()+" vous n'avez pas deviné le code secret","Ooooooooooups!",JOptionPane.INFORMATION_MESSAGE);
                      new JOptionPane().showMessageDialog(null,"Le code était: "+p.getCode().afficher(),"Code",JOptionPane.INFORMATION_MESSAGE);
                     Acceuil a=new Acceuil();
            a.setVisible(true);
            this.dispose(); 
            }
                 }
                 else{
             javax.swing.JOptionPane.showMessageDialog(null,"Désolé "+p.getActif().getPseudo()+" vous n'avez pas deviné le code secret","Ooooooooooups!",JOptionPane.INFORMATION_MESSAGE);
           /*  if(round%2==0)
            {*/
             JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(null, "Veuillez entrer le code "+p.getActif().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
           round++;
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
            s.setVisible(true);
            this.dispose();
          
        }
    }
       
        }
        
    }
     public void afficherResultat(JLabel j,Combinaison c){
        String temp="";
         for(int i=0;i<6;i++){
                
                       if(c.position.get(i)) {
                           temp=temp.concat("2 ");
                       } 
                       else{
                           if(c.bonnePioche.get(i)) {
                           temp=temp.concat("1 ");}
                           else
                           { temp=temp.concat("0 ");
                       } 
                       }
            }
       j.setText(temp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlateauJeuLvl3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JButton Qui;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel b101;
    private javax.swing.JLabel b102;
    private javax.swing.JLabel b103;
    private javax.swing.JLabel b104;
    private javax.swing.JLabel b105;
    private javax.swing.JLabel b106;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b26;
    private javax.swing.JLabel b31;
    private javax.swing.JLabel b32;
    private javax.swing.JLabel b33;
    private javax.swing.JLabel b34;
    private javax.swing.JLabel b35;
    private javax.swing.JLabel b36;
    private javax.swing.JLabel b41;
    private javax.swing.JLabel b42;
    private javax.swing.JLabel b43;
    private javax.swing.JLabel b44;
    private javax.swing.JLabel b45;
    private javax.swing.JLabel b46;
    private javax.swing.JLabel b51;
    private javax.swing.JLabel b52;
    private javax.swing.JLabel b53;
    private javax.swing.JLabel b54;
    private javax.swing.JLabel b55;
    private javax.swing.JLabel b56;
    private javax.swing.JLabel b61;
    private javax.swing.JLabel b62;
    private javax.swing.JLabel b63;
    private javax.swing.JLabel b64;
    private javax.swing.JLabel b65;
    private javax.swing.JLabel b66;
    private javax.swing.JLabel b71;
    private javax.swing.JLabel b72;
    private javax.swing.JLabel b73;
    private javax.swing.JLabel b74;
    private javax.swing.JLabel b75;
    private javax.swing.JLabel b76;
    private javax.swing.JLabel b81;
    private javax.swing.JLabel b82;
    private javax.swing.JLabel b83;
    private javax.swing.JLabel b84;
    private javax.swing.JLabel b85;
    private javax.swing.JLabel b86;
    private javax.swing.JLabel b91;
    private javax.swing.JLabel b92;
    private javax.swing.JLabel b93;
    private javax.swing.JLabel b94;
    private javax.swing.JLabel b95;
    private javax.swing.JLabel b96;
    private javax.swing.JLabel blanc;
    private javax.swing.JLabel bleue;
    private javax.swing.JLabel case1;
    private javax.swing.JLabel case10;
    private javax.swing.JLabel case2;
    private javax.swing.JLabel case3;
    private javax.swing.JLabel case4;
    private javax.swing.JLabel case5;
    private javax.swing.JLabel case6;
    private javax.swing.JLabel case7;
    private javax.swing.JLabel case8;
    private javax.swing.JLabel case9;
    private javax.swing.JLabel fondPalette;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jaune;
    private javax.swing.JLabel marron;
    private javax.swing.JLabel noir;
    private javax.swing.JLabel orange;
    private javax.swing.JLabel res1;
    private javax.swing.JLabel res10;
    private javax.swing.JLabel res2;
    private javax.swing.JLabel res3;
    private javax.swing.JLabel res4;
    private javax.swing.JLabel res5;
    private javax.swing.JLabel res6;
    private javax.swing.JLabel res7;
    private javax.swing.JLabel res8;
    private javax.swing.JLabel res9;
    private javax.swing.JLabel rose;
    private javax.swing.JLabel rouge;
    private javax.swing.JLabel verte;
    private javax.swing.JLabel violette;
    // End of variables declaration//GEN-END:variables
}
