/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetre;

import code.Combinaison;
import code.EcrivainScore;
import code.LecteurScore;
import code.Partie;
import java.beans.EventHandler;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * @author team : ALICHERIF Elhaous, MOUHAMAD Imame & NGUYEN Quang Minh
 **/
public class PlateauJeuLvl2 extends javax.swing.JFrame {

    code.Partie p;
    int l;
    int round;
    int compteur;
    ArrayList<JLabel> ensLabel = new ArrayList<>();
    ArrayList<String> colors = new ArrayList<>();

    /**
     * Creates new form PlateauJeuLvl2
     **/
    public PlateauJeuLvl2() {
        initComponents();
    }
    public PlateauJeuLvl2(code.Partie n) {
        initComponents();
        p = new Partie(0, null,0);
        p = n;
        l = 0;
        round=1;
        compteur = l;
        p.incEssai();
        ensLabel.add(b11);
        ensLabel.add(b12);
        ensLabel.add(b13);
        ensLabel.add(b14);
        ensLabel.add(b15);
        ensLabel.add(b21);
        ensLabel.add(b22);
        ensLabel.add(b23);
        ensLabel.add(b24);
        ensLabel.add(b25);
        ensLabel.add(b31);
        ensLabel.add(b32);
        ensLabel.add(b33);
        ensLabel.add(b34);
        ensLabel.add(b35);
        ensLabel.add(b41);
        ensLabel.add(b42);
        ensLabel.add(b43);
        ensLabel.add(b44);
        ensLabel.add(b45);
        ensLabel.add(b51);
        ensLabel.add(b52);
        ensLabel.add(b53);
        ensLabel.add(b54);
        ensLabel.add(b55);
        ensLabel.add(b61);
        ensLabel.add(b62);
        ensLabel.add(b63);
        ensLabel.add(b64);
        ensLabel.add(b65);
        ensLabel.add(b71);
        ensLabel.add(b72);
        ensLabel.add(b73);
        ensLabel.add(b74);
        ensLabel.add(b75);
        ensLabel.add(b81);
        ensLabel.add(b82);
        ensLabel.add(b83);
        ensLabel.add(b84);
        ensLabel.add(b85);
        ensLabel.add(b91);
        ensLabel.add(b92);
        ensLabel.add(b93);
        ensLabel.add(b94);
        ensLabel.add(b95);
        ensLabel.add(b101);
        ensLabel.add(b102);
        ensLabel.add(b103);
        ensLabel.add(b104);
        ensLabel.add(b105);
        
    p.getCode().afficher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        case1 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        case2 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        b23 = new javax.swing.JLabel();
        b24 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        case3 = new javax.swing.JLabel();
        b31 = new javax.swing.JLabel();
        b32 = new javax.swing.JLabel();
        b33 = new javax.swing.JLabel();
        b34 = new javax.swing.JLabel();
        b35 = new javax.swing.JLabel();
        case4 = new javax.swing.JLabel();
        b41 = new javax.swing.JLabel();
        b42 = new javax.swing.JLabel();
        b43 = new javax.swing.JLabel();
        b44 = new javax.swing.JLabel();
        b45 = new javax.swing.JLabel();
        case5 = new javax.swing.JLabel();
        b51 = new javax.swing.JLabel();
        b52 = new javax.swing.JLabel();
        b53 = new javax.swing.JLabel();
        b54 = new javax.swing.JLabel();
        b55 = new javax.swing.JLabel();
        case6 = new javax.swing.JLabel();
        b61 = new javax.swing.JLabel();
        b62 = new javax.swing.JLabel();
        b63 = new javax.swing.JLabel();
        b64 = new javax.swing.JLabel();
        b65 = new javax.swing.JLabel();
        case7 = new javax.swing.JLabel();
        b71 = new javax.swing.JLabel();
        b72 = new javax.swing.JLabel();
        b73 = new javax.swing.JLabel();
        b74 = new javax.swing.JLabel();
        b75 = new javax.swing.JLabel();
        case8 = new javax.swing.JLabel();
        b81 = new javax.swing.JLabel();
        b82 = new javax.swing.JLabel();
        b83 = new javax.swing.JLabel();
        b84 = new javax.swing.JLabel();
        b85 = new javax.swing.JLabel();
        case9 = new javax.swing.JLabel();
        b91 = new javax.swing.JLabel();
        b92 = new javax.swing.JLabel();
        b93 = new javax.swing.JLabel();
        b94 = new javax.swing.JLabel();
        b95 = new javax.swing.JLabel();
        case10 = new javax.swing.JLabel();
        b101 = new javax.swing.JLabel();
        b102 = new javax.swing.JLabel();
        b103 = new javax.swing.JLabel();
        b104 = new javax.swing.JLabel();
        b105 = new javax.swing.JLabel();
        lvl2_jLabel6 = new javax.swing.JLabel();
        lvl2_jLabel4 = new javax.swing.JLabel();
        Accueil = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        lvl2_jLabel5 = new javax.swing.JLabel();
        lblres10 = new javax.swing.JLabel();
        lblres1 = new javax.swing.JLabel();
        lblres2 = new javax.swing.JLabel();
        lblres3 = new javax.swing.JLabel();
        lblres4 = new javax.swing.JLabel();
        lblres5 = new javax.swing.JLabel();
        lblres6 = new javax.swing.JLabel();
        lblres9 = new javax.swing.JLabel();
        lvl2_jLabel3 = new javax.swing.JLabel();
        lblres8 = new javax.swing.JLabel();
        lblres7 = new javax.swing.JLabel();
        rose = new javax.swing.JLabel();
        noir = new javax.swing.JLabel();
        bleue = new javax.swing.JLabel();
        orange = new javax.swing.JLabel();
        blanc = new javax.swing.JLabel();
        violette = new javax.swing.JLabel();
        rouge = new javax.swing.JLabel();
        verte = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Qui = new javax.swing.JButton();
        plateau = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 695));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        case1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 575, -1, 50));

        b11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setToolTipText("");
        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b11MouseClicked(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 581, 34, 36));

        b12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setToolTipText("");
        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b12MouseClicked(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 581, 34, 36));

        b13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.setToolTipText("");
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b13MouseClicked(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 581, 34, 36));

        b14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b14.setToolTipText("");
        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b14MouseClicked(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 581, 34, 36));

        b15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b15.setToolTipText("");
        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b15MouseClicked(evt);
            }
        });
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 581, 34, 36));

        case2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 525, -1, 50));

        b21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b21.setToolTipText("");
        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b21MouseClicked(evt);
            }
        });
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 531, 34, 36));

        b22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b22.setToolTipText("");
        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b22MouseClicked(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 531, 34, 36));

        b23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b23.setToolTipText("");
        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b23MouseClicked(evt);
            }
        });
        getContentPane().add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 531, 34, 36));

        b24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b24.setToolTipText("");
        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b24MouseClicked(evt);
            }
        });
        getContentPane().add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 531, 34, 36));

        b25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b25.setToolTipText("");
        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b25MouseClicked(evt);
            }
        });
        getContentPane().add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 531, 34, 36));

        case3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 475, -1, 50));

        b31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b31.setToolTipText("");
        b31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b31MouseClicked(evt);
            }
        });
        getContentPane().add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 481, 34, 36));

        b32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b32.setToolTipText("");
        b32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b32MouseClicked(evt);
            }
        });
        getContentPane().add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 481, 34, 36));

        b33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b33.setToolTipText("");
        b33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b33MouseClicked(evt);
            }
        });
        getContentPane().add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 481, 34, 36));

        b34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b34.setToolTipText("");
        b34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b34MouseClicked(evt);
            }
        });
        getContentPane().add(b34, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 481, 34, 36));

        b35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b35MouseClicked(evt);
            }
        });
        getContentPane().add(b35, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 481, 34, 36));

        case4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 425, -1, 50));

        b41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b41.setToolTipText("");
        b41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b41MouseClicked(evt);
            }
        });
        getContentPane().add(b41, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 431, 34, 36));

        b42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b42MouseClicked(evt);
            }
        });
        getContentPane().add(b42, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 431, 34, 36));

        b43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b43.setToolTipText("");
        b43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b43MouseClicked(evt);
            }
        });
        getContentPane().add(b43, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 431, 34, 36));

        b44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b44MouseClicked(evt);
            }
        });
        getContentPane().add(b44, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 431, 34, 36));

        b45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b45MouseClicked(evt);
            }
        });
        getContentPane().add(b45, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 431, 34, 36));

        case5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 375, -1, 50));

        b51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b51.setToolTipText("");
        b51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b51MouseClicked(evt);
            }
        });
        getContentPane().add(b51, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 381, 34, 36));

        b52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b52.setToolTipText("");
        b52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b52MouseClicked(evt);
            }
        });
        getContentPane().add(b52, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 381, 34, 36));

        b53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b53.setToolTipText("");
        b53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b53MouseClicked(evt);
            }
        });
        getContentPane().add(b53, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 381, 34, 36));

        b54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b54.setToolTipText("");
        b54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b54MouseClicked(evt);
            }
        });
        getContentPane().add(b54, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 381, 34, 36));

        b55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b55.setToolTipText("");
        b55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b55MouseClicked(evt);
            }
        });
        getContentPane().add(b55, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 381, 34, 36));

        case6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, -1, 50));

        b61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b61.setToolTipText("");
        b61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b61MouseClicked(evt);
            }
        });
        getContentPane().add(b61, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 331, 34, 36));

        b62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b62.setToolTipText("");
        b62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b62MouseClicked(evt);
            }
        });
        getContentPane().add(b62, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 331, 34, 36));

        b63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b63.setToolTipText("");
        b63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b63MouseClicked(evt);
            }
        });
        getContentPane().add(b63, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 331, 34, 36));

        b64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b64.setToolTipText("");
        b64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b64MouseClicked(evt);
            }
        });
        getContentPane().add(b64, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 331, 34, 36));

        b65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b65.setToolTipText("");
        b65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b65MouseClicked(evt);
            }
        });
        getContentPane().add(b65, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 331, 34, 36));

        case7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 275, -1, 50));

        b71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b71.setToolTipText("");
        b71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b71MouseClicked(evt);
            }
        });
        getContentPane().add(b71, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 281, 34, 36));

        b72.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b72.setToolTipText("");
        b72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b72MouseClicked(evt);
            }
        });
        getContentPane().add(b72, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 281, 34, 36));

        b73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b73.setToolTipText("");
        b73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b73MouseClicked(evt);
            }
        });
        getContentPane().add(b73, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 281, 34, 36));

        b74.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b74.setToolTipText("");
        b74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b74MouseClicked(evt);
            }
        });
        getContentPane().add(b74, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 281, 34, 36));

        b75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b75.setToolTipText("");
        b75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b75MouseClicked(evt);
            }
        });
        getContentPane().add(b75, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 281, 34, 36));

        case8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, -1, 50));

        b81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b81.setToolTipText("");
        b81.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b81MouseClicked(evt);
            }
        });
        getContentPane().add(b81, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 231, 34, 36));

        b82.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b82.setToolTipText("");
        b82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b82MouseClicked(evt);
            }
        });
        getContentPane().add(b82, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 231, 34, 36));

        b83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b83.setToolTipText("");
        b83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b83MouseClicked(evt);
            }
        });
        getContentPane().add(b83, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 231, 34, 36));

        b84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b84.setToolTipText("");
        b84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b84MouseClicked(evt);
            }
        });
        getContentPane().add(b84, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 231, 34, 36));

        b85.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b85.setToolTipText("");
        b85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b85MouseClicked(evt);
            }
        });
        getContentPane().add(b85, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 231, 34, 36));

        case9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 175, -1, 50));

        b91.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b91MouseClicked(evt);
            }
        });
        getContentPane().add(b91, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 181, 34, 36));

        b92.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b92.setToolTipText("");
        b92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b92MouseClicked(evt);
            }
        });
        getContentPane().add(b92, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 181, 34, 36));

        b93.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b93.setToolTipText("");
        b93.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b93MouseClicked(evt);
            }
        });
        getContentPane().add(b93, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 181, 34, 36));

        b94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b94.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b94MouseClicked(evt);
            }
        });
        getContentPane().add(b94, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 181, 34, 36));

        b95.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b95.setToolTipText("");
        b95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b95MouseClicked(evt);
            }
        });
        getContentPane().add(b95, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 181, 34, 36));

        case10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/case2tr.png"))); // NOI18N
        getContentPane().add(case10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, -1, 50));

        b101.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b101.setToolTipText("");
        b101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b101MouseClicked(evt);
            }
        });
        getContentPane().add(b101, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 131, 34, 36));

        b102.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b102MouseClicked(evt);
            }
        });
        getContentPane().add(b102, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 131, 34, 36));

        b103.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b103MouseClicked(evt);
            }
        });
        getContentPane().add(b103, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 131, 34, 36));

        b104.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b104.setToolTipText("");
        b104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b104MouseClicked(evt);
            }
        });
        getContentPane().add(b104, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 131, 34, 36));

        b105.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b105.setToolTipText("");
        b105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b105MouseClicked(evt);
            }
        });
        getContentPane().add(b105, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 131, 34, 36));

        lvl2_jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        lvl2_jLabel6.setText("Palette de couleurs :");
        getContentPane().add(lvl2_jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        lvl2_jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lvl2_jLabel4.setText("Astuces :");
        getContentPane().add(lvl2_jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        Accueil.setText("Accueil");
        Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilActionPerformed(evt);
            }
        });
        getContentPane().add(Accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 70, -1));

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl2_ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 70, -1));

        lvl2_jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lvl2_jLabel5.setText("<html> <p>1 --> Bonne couleur mais mauvaise position   <p> <p> <p>2  -->  Bonne couleur et bonne position  </html>");
        getContentPane().add(lvl2_jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        lblres10.setBackground(new java.awt.Color(0, 0, 0));
        lblres10.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres10.setForeground(new java.awt.Color(255, 255, 255));
        lblres10.setText("* * * * *");
        lblres10.setToolTipText("");
        lblres10.setOpaque(true);
        getContentPane().add(lblres10, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 135, -1, 30));

        lblres1.setBackground(new java.awt.Color(0, 0, 0));
        lblres1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres1.setForeground(new java.awt.Color(255, 255, 255));
        lblres1.setText("* * * * *");
        lblres1.setOpaque(true);
        getContentPane().add(lblres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 585, -1, 30));

        lblres2.setBackground(new java.awt.Color(0, 0, 0));
        lblres2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres2.setForeground(new java.awt.Color(255, 255, 255));
        lblres2.setText("* * * * *");
        lblres2.setOpaque(true);
        getContentPane().add(lblres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 535, -1, 30));

        lblres3.setBackground(new java.awt.Color(0, 0, 0));
        lblres3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres3.setForeground(new java.awt.Color(255, 255, 255));
        lblres3.setText("* * * * *");
        lblres3.setOpaque(true);
        getContentPane().add(lblres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 485, -1, 30));

        lblres4.setBackground(new java.awt.Color(0, 0, 0));
        lblres4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres4.setForeground(new java.awt.Color(255, 255, 255));
        lblres4.setText("* * * * *");
        lblres4.setOpaque(true);
        getContentPane().add(lblres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 435, -1, 30));

        lblres5.setBackground(new java.awt.Color(0, 0, 0));
        lblres5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres5.setForeground(new java.awt.Color(255, 255, 255));
        lblres5.setText("* * * * * ");
        lblres5.setOpaque(true);
        getContentPane().add(lblres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 385, -1, 30));
        lblres5.getAccessibleContext().setAccessibleName("* * * * *");

        lblres6.setBackground(new java.awt.Color(0, 0, 0));
        lblres6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres6.setForeground(new java.awt.Color(255, 255, 255));
        lblres6.setText("* * * * *");
        lblres6.setOpaque(true);
        getContentPane().add(lblres6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 335, -1, 30));
        lblres6.getAccessibleContext().setAccessibleName("* * * *");

        lblres9.setBackground(new java.awt.Color(0, 0, 0));
        lblres9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres9.setForeground(new java.awt.Color(255, 255, 255));
        lblres9.setText("* * * * *");
        lblres9.setOpaque(true);
        getContentPane().add(lblres9, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 185, -1, 30));

        lvl2_jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/master_mind_logo.jpg"))); // NOI18N
        getContentPane().add(lvl2_jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 15, 500, 70));

        lblres8.setBackground(new java.awt.Color(0, 0, 0));
        lblres8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres8.setForeground(new java.awt.Color(255, 255, 255));
        lblres8.setText("* * * * *");
        lblres8.setOpaque(true);
        getContentPane().add(lblres8, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 235, -1, 30));

        lblres7.setBackground(new java.awt.Color(0, 0, 0));
        lblres7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblres7.setForeground(new java.awt.Color(255, 255, 255));
        lblres7.setText("* * * * *");
        lblres7.setOpaque(true);
        getContentPane().add(lblres7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 285, -1, 30));

        rose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rose.jpg"))); // NOI18N
        rose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseMouseClicked(evt);
            }
        });
        getContentPane().add(rose, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 50));

        noir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/noir.jpg"))); // NOI18N
        noir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noirMouseClicked(evt);
            }
        });
        getContentPane().add(noir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        bleue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bleue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bleu.jpg"))); // NOI18N
        bleue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bleueMouseClicked(evt);
            }
        });
        getContentPane().add(bleue, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        orange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/orange.png"))); // NOI18N
        orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeMouseClicked(evt);
            }
        });
        getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 60, 50));

        blanc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.jpg"))); // NOI18N
        blanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancMouseClicked(evt);
            }
        });
        getContentPane().add(blanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 40, -1));

        violette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        violette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/violet.jpg"))); // NOI18N
        violette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                violetteMouseClicked(evt);
            }
        });
        getContentPane().add(violette, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, 50));

        rouge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rouge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rouge.jpg"))); // NOI18N
        rouge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rougeMouseClicked(evt);
            }
        });
        getContentPane().add(rouge, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 40));

        verte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vert.jpg"))); // NOI18N
        verte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verteMouseClicked(evt);
            }
        });
        getContentPane().add(verte, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 240, 230));

        Qui.setText("Qui joue ?");
        Qui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuiActionPerformed(evt);
            }
        });
        getContentPane().add(Qui, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        plateau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FOND JEU - Copie.jpg"))); // NOI18N
        plateau.setMaximumSize(new java.awt.Dimension(389, 900));
        plateau.setMinimumSize(new java.awt.Dimension(389, 900));
        plateau.setPreferredSize(new java.awt.Dimension(389, 900));
        getContentPane().add(plateau, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, 340, 550));

        fond.setBackground(new java.awt.Color(0, 0, 0));
        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fond-gris-galyoneo.jpg"))); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lvl2_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl2_ValiderActionPerformed
        if(compteur==5){
            noir.setVisible(true);
            blanc.setVisible(true);
            rouge.setVisible(true);
            bleue.setVisible(true);
            rose.setVisible(true);
            verte.setVisible(true);
            violette.setVisible(true);
            orange.setVisible(true);
      
            switch(p.getEssai()){
                case 1: Combinaison c=new Combinaison();
                    for(int i=0;i<5;i++){
                        c.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c);
                    p.verifier(c);
                    afficherResultat(lblres1, c);
                    checkFin();
                    p.incEssai();
                    break;
                case 2: Combinaison c1=new Combinaison();
                    for(int i=5;i<10;i++){
                        c1.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c1);
                    p.verifier(c1);
                    afficherResultat(lblres2, c1);
                    checkFin();
                    p.incEssai();
                    break;
                case 3: Combinaison c2=new Combinaison();
                    for(int i=10;i<15;i++){
                        c2.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c2);
                    p.verifier(c2);
                    afficherResultat(lblres3, c2);
                    checkFin();
                    p.incEssai();
                    break; 
                case 4: Combinaison c3=new Combinaison();
                    for(int i=15;i<20;i++){
                        c3.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c3);
                    p.verifier(c3);
                    afficherResultat(lblres4, c3);
                    checkFin();
                    p.incEssai();
                    break;
                case 5: Combinaison c4=new Combinaison();
                    for(int i=20;i<25;i++){
                        c4.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c4);
                    p.verifier(c4);
                    afficherResultat(lblres5, c4);
                    checkFin();
                    p.incEssai();
                    break; 
                case 6: Combinaison c5=new Combinaison();
                    for(int i=25;i<30;i++){
                        c5.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c5);
                    p.verifier(c5);
                    afficherResultat(lblres6, c5);
                    checkFin();
                    p.incEssai();
                    break;
                case 7: Combinaison c6=new Combinaison();
                    for(int i=30;i<35;i++){
                        c6.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c6);
                    p.verifier(c6);
                    afficherResultat(lblres7, c6);
                    checkFin();
                    p.incEssai();
                    break; 
                case 8: Combinaison c7=new Combinaison();
                    for(int i=35;i<40;i++){
                        c7.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c7);
                    p.verifier(c7);
                    afficherResultat(lblres8, c7);
                    checkFin();
                    p.incEssai();
                    break;
                case 9: Combinaison c8=new Combinaison();
                    for(int i=40;i<45;i++){
                        c8.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c8);
                    p.verifier(c8);
                    afficherResultat(lblres9, c8);
                    checkFin();
                    p.incEssai();
                    break;
                case 10: Combinaison c9=new Combinaison();
                    for(int i=45;i<50;i++){
                        c9.ajouterBoule(code.Couleur.corCouleur(colors.get(i))); 
                    }
                    p.ajouterCombinaison(c9);
                    p.verifier(c9);
                    afficherResultat(lblres10, c9);
                    checkFin();
                    p.incEssai();
                    break;
            }   
        compteur = 0;     
    }//GEN-LAST:event_lvl2_ValiderActionPerformed
        else{
           new JOptionPane().showMessageDialog(null,"Vous devez choisir 5 couleurs","Erreur",JOptionPane.ERROR_MESSAGE);
        }
   } 
   
     /**
     * les casesMouseClicked : enlever les couleurs présentées
     */
    private void b11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseClicked
        if(l<6){
            if(b11.getIcon()!=null){
                b11.setIcon(null);
                b12.setIcon(null);
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                l=0;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b11MouseClicked
    private void b21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b21MouseClicked
        if(l<11){
            if(b21.getIcon()!=null){
                b21.setIcon(null);
                b22.setIcon(null);
                b23.setIcon(null);
                b24.setIcon(null);
                b25.setIcon(null);
                l=5;
                compteur=0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b21MouseClicked
    private void b31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b31MouseClicked
        if(l<16){
            if(b31.getIcon()!=null){
                b31.setIcon(null);
                b32.setIcon(null);
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                l=10;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b31MouseClicked
    private void b41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b41MouseClicked
        if(l<21){
            if(b41.getIcon()!=null){
                b41.setIcon(null);
                b42.setIcon(null);
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                l=15;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b41MouseClicked
    private void b51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b51MouseClicked
        if(l<26){
            if(b51.getIcon()!=null){
                b51.setIcon(null);
                b52.setIcon(null);
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                l=20;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b51MouseClicked
    private void b61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b61MouseClicked
        if(l<31){
            if(b61.getIcon()!=null){
                b61.setIcon(null);
                b62.setIcon(null);
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                l=25;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b61MouseClicked
    private void b71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b71MouseClicked
        if(l<36){
            if(b71.getIcon()!=null){
                b71.setIcon(null);
                b72.setIcon(null);
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                l=30;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b71MouseClicked
    private void b81MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b81MouseClicked
        if(l<41){
            if(b81.getIcon()!=null){
                b81.setIcon(null);
                b82.setIcon(null);
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                l=35;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b81MouseClicked
    private void b91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b91MouseClicked
        if(l<46){
            if(b91.getIcon()!=null){
                b91.setIcon(null);
                b92.setIcon(null);
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                l=40;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b91MouseClicked
    private void b101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b101MouseClicked
        if(l<51){
            if(b101.getIcon()!=null){
                b101.setIcon(null);
                b102.setIcon(null);
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                l=45;
                compteur = 0;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b101MouseClicked
    private void b12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b12MouseClicked
        if(l<6){
            if(b12.getIcon()!=null){
                b12.setIcon(null);
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                l=1;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b12MouseClicked
    private void b22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b22MouseClicked
        if(l<11){
            if(b22.getIcon()!=null){
                b22.setIcon(null);
                b23.setIcon(null);
                b24.setIcon(null);
                b25.setIcon(null);
                l=6;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b22MouseClicked
    private void b32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b32MouseClicked
        if(l<16){
            if(b32.getIcon()!=null){
                b32.setIcon(null);
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                l=11;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b32MouseClicked
    private void b42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b42MouseClicked
        if(l<21){
            if(b42.getIcon()!=null){
                b42.setIcon(null);
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                l=16;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b42MouseClicked
    private void b52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b52MouseClicked
        if(l<26){
            if(b52.getIcon()!=null){
                b52.setIcon(null);
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                l=21;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b52MouseClicked
    private void b62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b62MouseClicked
        if(l<31){
            if(b62.getIcon()!=null){
                b62.setIcon(null);
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                l=26;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b62MouseClicked
    private void b72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b72MouseClicked
        if(l<36){
            if(b72.getIcon()!=null){
                b72.setIcon(null);
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                l=31;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b72MouseClicked
    private void b82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b82MouseClicked
        if(l<41){
            if(b82.getIcon()!=null){
                b82.setIcon(null);
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                l=36;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b82MouseClicked
    private void b92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b92MouseClicked
        if(l<46){
            if(b92.getIcon()!=null){
                b92.setIcon(null);
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                l=41;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b92MouseClicked
    private void b102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b102MouseClicked
        if(l<51){
            if(b102.getIcon()!=null){
                b102.setIcon(null);
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                l=46;
                compteur = 1;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b102MouseClicked
    private void b13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseClicked
        if(l<6){
            if(b13.getIcon()!=null){
                b13.setIcon(null);
                b14.setIcon(null);
                b15.setIcon(null);
                l=2;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b13MouseClicked
    private void b23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b23MouseClicked
        if(l<11){
            if(b23.getIcon()!=null){
                b23.setIcon(null);
                b24.setIcon(null);
                b25.setIcon(null);
                l=7;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b23MouseClicked
    private void b33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b33MouseClicked
        if(l<16){
            if(b33.getIcon()!=null){
                b33.setIcon(null);
                b34.setIcon(null);
                b35.setIcon(null);
                l=12;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b33MouseClicked
    private void b43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b43MouseClicked
        if(l<21){
            if(b43.getIcon()!=null){
                b43.setIcon(null);
                b44.setIcon(null);
                b45.setIcon(null);
                l=17;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b43MouseClicked
    private void b53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b53MouseClicked
        if(l<26){
            if(b53.getIcon()!=null){
                b53.setIcon(null);
                b54.setIcon(null);
                b55.setIcon(null);
                l=22;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b53MouseClicked
    private void b63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b63MouseClicked
        if(l<31){
            if(b63.getIcon()!=null){
                b63.setIcon(null);
                b64.setIcon(null);
                b65.setIcon(null);
                l=27;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b63MouseClicked
    private void b73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b73MouseClicked
        if(l<36){
            if(b73.getIcon()!=null){
                b73.setIcon(null);
                b74.setIcon(null);
                b75.setIcon(null);
                l=32;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b73MouseClicked
    private void b83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b83MouseClicked
        if(l<41){
            if(b83.getIcon()!=null){
                b83.setIcon(null);
                b84.setIcon(null);
                b85.setIcon(null);
                l=37;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b83MouseClicked
    private void b93MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b93MouseClicked
        if(l<46){
            if(b93.getIcon()!=null){
                b93.setIcon(null);
                b94.setIcon(null);
                b95.setIcon(null);
                l=42;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b93MouseClicked
    private void b103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b103MouseClicked
        if(l<51){
            if(b103.getIcon()!=null){
                b103.setIcon(null);
                b104.setIcon(null);
                b105.setIcon(null);
                l=47;
                compteur = 2;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b103MouseClicked
    private void b14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b14MouseClicked
        if(l<6){
            if(b14.getIcon()!=null){
                b14.setIcon(null);
                b15.setIcon(null);
                l=3;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b14MouseClicked
    private void b24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b24MouseClicked
        if(l<11){
            if(b24.getIcon()!=null){
                b24.setIcon(null);
                b25.setIcon(null);
                l=8;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b24MouseClicked
    private void b34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b34MouseClicked
        if(l<16){
            if(b34.getIcon()!=null){
                b34.setIcon(null);
                b35.setIcon(null);
                l=13;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b34MouseClicked
    private void b44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b44MouseClicked
        if(l<21){
            if(b44.getIcon()!=null){
                b44.setIcon(null);
                b45.setIcon(null);
                l=18;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b44MouseClicked
    private void b54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b54MouseClicked
        if(l<26){
            if(b54.getIcon()!=null){
                b54.setIcon(null);
                b55.setIcon(null);
                l=23;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b54MouseClicked
    private void b64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b64MouseClicked
        if(l<31){
            if(b64.getIcon()!=null){
                b64.setIcon(null);
                b65.setIcon(null);
                l=28;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b64MouseClicked
    private void b74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b74MouseClicked
        if(l<36){
            if(b74.getIcon()!=null){
                b74.setIcon(null);
                b75.setIcon(null);
                l=33;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b74MouseClicked
    private void b84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b84MouseClicked
        if(l<41){
            if(b84.getIcon()!=null){
                b84.setIcon(null);
                b85.setIcon(null);
                l=38;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b84MouseClicked
    private void b94MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b94MouseClicked
        if(l<46){
            if(b94.getIcon()!=null){
                b94.setIcon(null);
                b95.setIcon(null);
                l=43;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b94MouseClicked
    private void b104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b104MouseClicked
        if(l<51){
            if(b104.getIcon()!=null){
                b104.setIcon(null);
                b105.setIcon(null);
                l=48;
                compteur = 3;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b104MouseClicked
    private void b15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b15MouseClicked
        if(l<6){
            if(b15.getIcon()!=null){
                b15.setIcon(null);
                l=4;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b15MouseClicked
    private void b25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b25MouseClicked
        if(l<11){
            if(b25.getIcon()!=null){
                b25.setIcon(null);
                l=9;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b25MouseClicked
    private void b35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b35MouseClicked
        if(l<16){
            if(b35.getIcon()!=null){
                b35.setIcon(null);
                l=14;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b35MouseClicked
    private void b45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b45MouseClicked
        if(l<21){
            if(b45.getIcon()!=null){
                b45.setIcon(null);
                l=19;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b45MouseClicked
    private void b55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b55MouseClicked
        if(l<26){
            if(b55.getIcon()!=null){
                b55.setIcon(null);
                l=24;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b55MouseClicked
    private void b65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b65MouseClicked
        if(l<31){
            if(b65.getIcon()!=null){
                b65.setIcon(null);
                l=29;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b65MouseClicked
    private void b75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b75MouseClicked
        if(l<36){
            if(b75.getIcon()!=null){
                b75.setIcon(null);
                l=34;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b75MouseClicked
    private void b85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b85MouseClicked
        if(l<41){
            if(b85.getIcon()!=null){
                b85.setIcon(null);
                l=39;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b85MouseClicked
    private void b95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b95MouseClicked
        if(l<46){
            if(b95.getIcon()!=null){
                b95.setIcon(null);
                l=44;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b95MouseClicked
    private void b105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b105MouseClicked
        if(l<51){
            if(b105.getIcon()!=null){
                b105.setIcon(null);
                l=49;
                compteur = 4;
                colors=maj_colors(colors,l);
            }
        }
    }//GEN-LAST:event_b105MouseClicked
   
    public ArrayList<String> maj_colors(ArrayList<String> c, int l){
        ArrayList<String> res=new ArrayList<>();
        int i;
        for(i=0; i<l; i++){
            res.add(c.get(i));
        }
        return res;
    }   
        
    /**
     * les colorMouseClicked : importer les couler selectionées
     */
    private void bleueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bleueMouseClicked
         if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bleu.jpg")));
        colors.add("B");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bleueMouseClicked
    private void roseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseMouseClicked
     if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rose.jpg")));
        colors.add("P");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_roseMouseClicked
    private void orangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeMouseClicked
        if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/orange.png")));
        colors.add("O");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orangeMouseClicked
    private void noirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noirMouseClicked
        if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/noir.jpg")));
        colors.add("N");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_noirMouseClicked
    private void violetteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_violetteMouseClicked
        if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/violet.jpg")));
        colors.add("V");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_violetteMouseClicked
    private void rougeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rougeMouseClicked
      if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rouge.jpg")));
        colors.add("R");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rougeMouseClicked
    private void blancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancMouseClicked
        if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blanc.jpg")));
        colors.add("W");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_blancMouseClicked
    private void verteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verteMouseClicked
        if(compteur != 5  ){
        ensLabel.get(l).setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vert.jpg")));
        colors.add("G");
        l++;
        compteur ++;
        }
        else {
       new JOptionPane().showMessageDialog(null,"Vous devez d'abord valider","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verteMouseClicked

    private void AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilActionPerformed
        Acceuil a=new Acceuil();
                a.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_AccueilActionPerformed

    private void QuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuiActionPerformed
        new JOptionPane().showMessageDialog(null, "C'est le tour de "+p.getActif().getPseudo()+" jouer!","Joueur Actif",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_QuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlateauJeuLvl2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlateauJeuLvl2().setVisible(true);
            }
        });
    }
    
     public void checkFinDuel(){
      if(p.getActif().getEssai()==100){
            if(p.getJoueur().getRecord()>p.getJoueur2().getRecord())
            { new JOptionPane().showMessageDialog(null, "Désolé "+p.getJoueur2().getPseudo()+"!!!\n vous avez perdu","Fin de partie",JOptionPane.INFORMATION_MESSAGE);
             Acceuil a=new Acceuil();
            this.dispose();
            }
            else{
              new JOptionPane().showMessageDialog(null, "Désolé "+p.getJoueur().getPseudo()+"!!!\n vous avez perdu","Fin de partie",JOptionPane.INFORMATION_MESSAGE);
             Acceuil a=new Acceuil();
            this.dispose();
            }
           
    }}
     
     public void checkFin(){int r;
        if((p.getEssai()==10)||(p.getFin())){
            p.getActif().setEssai(p.getEssai());
            if(p.getFin()){
            javax.swing.JOptionPane.showMessageDialog(null,"Felicitation "+p.getActif().getPseudo()+" vous avez deviné le code secret" ,"Yatta",JOptionPane.INFORMATION_MESSAGE);
            new JOptionPane().showMessageDialog(null,"Le code était: "+p.getCode().afficher(),"Code",JOptionPane.INFORMATION_MESSAGE);
            p.getActif().setRecord(10-p.getEssai()+1);
            r= p.getActif().getRecord();
            if(p.getType()==1){
                Acceuil a=new Acceuil();
                a.setVisible(true);
                this.dispose();
                 }
                 else{
                checkFinDuel();
                if(round%2==0)
                {
                 JOptionPane jop = new JOptionPane();
                 JOptionPane jop2 = new JOptionPane();
            
            jop2.showMessageDialog(null,"Nombre d'essai : "+p.getJoueur().getPseudo()+" : "+p.getJoueur().getEssai()+" \n"+p.getJoueur2().getPseudo()+" : "+p.getJoueur2().getEssai(),"Score",JOptionPane.INFORMATION_MESSAGE);
            round ++;
            jop.showMessageDialog(null, "Veuillez entrer le code "+p.getJoueur2().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
    
            s.setVisible(true);
            this.dispose();
            }
            else{
             
               JOptionPane jop = new JOptionPane();
               JOptionPane jop2 = new JOptionPane();
           jop2.showMessageDialog(null,"Nombre d'essai :"+p.getJoueur().getPseudo()+" : "+p.getJoueur().getEssai()+" \n"+p.getJoueur2().getPseudo()+" : "+p.getJoueur2().getEssai(),"Score",JOptionPane.INFORMATION_MESSAGE);
            round++;
              jop.showMessageDialog(null, "Veuillez entrer le code "+p.getActif().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
           
            s.setVisible(true); 
            
             this.dispose();
            }
           
            }
                  File f=new File("scoreMoyen.txt");
            if(f.exists()){
            code.LecteurScore l=new LecteurScore("scoreMoyen.txt");
            String score=l.lecture();
            System.out.println(score);
            int k=score.indexOf(":");
            String alire=score.substring(k+1, score.length());
            k=Integer.parseInt(alire);
            if(k<r){
               code.EcrivainScore e=new EcrivainScore(p.getActif().getPseudo(), 10-p.getEssai()+1,"scoreMoyen.txt");  
            }
            }
           else
            {
                code.EcrivainScore e=new EcrivainScore(p.getActif().getPseudo(), 10-p.getEssai()+1,"scoreMoyen.txt");
            }
            }     
        else{
            if(p.getEssai()==10){
                 if(p.getType()==1){
                     javax.swing.JOptionPane.showMessageDialog(null,"Désolé "+p.getJoueur().getPseudo()+" vous n'avez pas deviné le code secret","Ooooooooooups!",JOptionPane.INFORMATION_MESSAGE);
                      new JOptionPane().showMessageDialog(null,"Le code était: "+p.getCode().afficher(),"Code",JOptionPane.INFORMATION_MESSAGE);
                     Acceuil a=new Acceuil();
            a.setVisible(true);
            this.dispose(); 
            }
                 }
                 else{
             javax.swing.JOptionPane.showMessageDialog(null,"Désolé "+p.getActif().getPseudo()+" vous n'avez pas deviné le code secret","Ooooooooooups!",JOptionPane.INFORMATION_MESSAGE);
             if(round%2==0)
            {
             JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(null, "Veuillez entrer le code "+p.getActif().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
           round++;
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
            s.setVisible(true);
            this.dispose();
            }
            else{
             JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(null, "Veuillez entrer le code "+p.getActif().getPseudo(), "Manche "+round, JOptionPane.INFORMATION_MESSAGE);
            round++;
            SelecteurCouleur s=new SelecteurCouleur(p.getNiveau(), p.getJoueur(), p.getJoueur2(),round);
            
            s.setVisible(true); 
             this.dispose();
            }
        }
    }
       
        }
                
    }
     public void afficherResultat(JLabel j,Combinaison c){
        String temp="";
         for(int i=0;i<5;i++){
                
                       if(c.position.get(i)) {
                           temp=temp.concat("2 ");
                       } 
                       else{
                           if(c.bonnePioche.get(i)) {
                           temp=temp.concat("1 ");}
                           else
                           { temp=temp.concat("0 ");
                       } 
                       }
            }
       j.setText(temp);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JButton Qui;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel b101;
    private javax.swing.JLabel b102;
    private javax.swing.JLabel b103;
    private javax.swing.JLabel b104;
    private javax.swing.JLabel b105;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b31;
    private javax.swing.JLabel b32;
    private javax.swing.JLabel b33;
    private javax.swing.JLabel b34;
    private javax.swing.JLabel b35;
    private javax.swing.JLabel b41;
    private javax.swing.JLabel b42;
    private javax.swing.JLabel b43;
    private javax.swing.JLabel b44;
    private javax.swing.JLabel b45;
    private javax.swing.JLabel b51;
    private javax.swing.JLabel b52;
    private javax.swing.JLabel b53;
    private javax.swing.JLabel b54;
    private javax.swing.JLabel b55;
    private javax.swing.JLabel b61;
    private javax.swing.JLabel b62;
    private javax.swing.JLabel b63;
    private javax.swing.JLabel b64;
    private javax.swing.JLabel b65;
    private javax.swing.JLabel b71;
    private javax.swing.JLabel b72;
    private javax.swing.JLabel b73;
    private javax.swing.JLabel b74;
    private javax.swing.JLabel b75;
    private javax.swing.JLabel b81;
    private javax.swing.JLabel b82;
    private javax.swing.JLabel b83;
    private javax.swing.JLabel b84;
    private javax.swing.JLabel b85;
    private javax.swing.JLabel b91;
    private javax.swing.JLabel b92;
    private javax.swing.JLabel b93;
    private javax.swing.JLabel b94;
    private javax.swing.JLabel b95;
    private javax.swing.JLabel blanc;
    private javax.swing.JLabel bleue;
    private javax.swing.JLabel case1;
    private javax.swing.JLabel case10;
    private javax.swing.JLabel case2;
    private javax.swing.JLabel case3;
    private javax.swing.JLabel case4;
    private javax.swing.JLabel case5;
    private javax.swing.JLabel case6;
    private javax.swing.JLabel case7;
    private javax.swing.JLabel case8;
    private javax.swing.JLabel case9;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblres1;
    private javax.swing.JLabel lblres10;
    private javax.swing.JLabel lblres2;
    private javax.swing.JLabel lblres3;
    private javax.swing.JLabel lblres4;
    private javax.swing.JLabel lblres5;
    private javax.swing.JLabel lblres6;
    private javax.swing.JLabel lblres7;
    private javax.swing.JLabel lblres8;
    private javax.swing.JLabel lblres9;
    private javax.swing.JLabel lvl2_jLabel3;
    private javax.swing.JLabel lvl2_jLabel4;
    private javax.swing.JLabel lvl2_jLabel5;
    private javax.swing.JLabel lvl2_jLabel6;
    private javax.swing.JLabel noir;
    private javax.swing.JLabel orange;
    private javax.swing.JLabel plateau;
    private javax.swing.JLabel rose;
    private javax.swing.JLabel rouge;
    private javax.swing.JLabel verte;
    private javax.swing.JLabel violette;
    // End of variables declaration//GEN-END:variables
}
