/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fenetre;
import code.Couleur;
import java.util.*;
import javax.swing.JComboBox;
/**
 *
 * @author team : ALICHERIF Elhaous, MOUHAMAD Imame & NGUYEN Quang Minh
 */
public class SelecteurCouleur extends javax.swing.JFrame {

    /**
     * Creates new form SelecteurCouleur
     */
    int n;
    code.Joueur j;
    code.Joueur k;
    int c;
    public SelecteurCouleur() {
        initComponents();
        
    }
    
    public SelecteurCouleur(int niveau,code.Joueur b,code.Joueur g, int i){
       initComponents();
       n=niveau;
       j=b;
       k=g;
       c=i;
        remplirCombo(jc1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox();
        jc3 = new javax.swing.JComboBox();
        jc4 = new javax.swing.JComboBox();
        jc5 = new javax.swing.JComboBox();
        jc6 = new javax.swing.JComboBox();
        jc2 = new javax.swing.JComboBox();
        btnAnnuler = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choix du code");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Couleur 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 23, 76, 23));

        jLabel2.setText("Couleur 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 67, -1, -1));

        jLabel3.setText("Couleur 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 107, -1, -1));

        jLabel4.setText("Couleur 4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 148, -1, -1));

        jLabel5.setText("Couleur 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 187, -1, -1));

        jLabel6.setText("Couleur 6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 228, -1, -1));

        jc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 24, 121, -1));

        jc3.setEnabled(false);
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3ActionPerformed(evt);
            }
        });
        getContentPane().add(jc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 104, 121, -1));

        jc4.setEnabled(false);
        jc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc4ActionPerformed(evt);
            }
        });
        getContentPane().add(jc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 142, 121, -1));

        jc5.setEnabled(false);
        jc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc5ActionPerformed(evt);
            }
        });
        getContentPane().add(jc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 184, 121, -1));

        jc6.setEnabled(false);
        jc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc6ActionPerformed(evt);
            }
        });
        getContentPane().add(jc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 222, 121, -1));

        jc2.setEnabled(false);
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });
        getContentPane().add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 64, 121, -1));

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        getContentPane().add(btnValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fond-gris-galyoneo.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        Acceuil ac=new Acceuil();
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
         remplirCombo(jc2);
        jc2.setEnabled(true);
    }//GEN-LAST:event_jc1ActionPerformed

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
        remplirCombo(jc3);
        jc3.setEnabled(true);
    }//GEN-LAST:event_jc2ActionPerformed

    private void jc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3ActionPerformed
        remplirCombo(jc4);
        jc4.setEnabled(true);
    }//GEN-LAST:event_jc3ActionPerformed

    private void jc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc4ActionPerformed
        
       if((n==5)||(n==6)){
           remplirCombo(jc5);
           jc5.setEnabled(true);
       }
    }//GEN-LAST:event_jc4ActionPerformed

    private void jc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc5ActionPerformed
       if(n==6)
       {
            remplirCombo(jc6);
           jc6.setEnabled(true);
       
       }
    }//GEN-LAST:event_jc5ActionPerformed

    private void jc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc6ActionPerformed
        
    }//GEN-LAST:event_jc6ActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        ArrayList<code.Couleur> co=new ArrayList<>();
         code.Partie p;
        switch(n){
            case 4: co.add(creationCode(jc1.getSelectedItem().toString()));
                    co.add(creationCode(jc2.getSelectedItem().toString()));
                    co.add(creationCode(jc3.getSelectedItem().toString()));
                    co.add(creationCode(jc4.getSelectedItem().toString()));
                    p=new code.Partie(n,j,k,co,2,c);
                    new PlateauJeu(p).setVisible(true);this.dispose();
                    break;
                
            case 5: co.add(creationCode(jc1.getSelectedItem().toString()));
                    co.add(creationCode(jc2.getSelectedItem().toString()));
                    co.add(creationCode(jc3.getSelectedItem().toString()));
                    co.add(creationCode(jc4.getSelectedItem().toString()));
                    co.add(creationCode(jc5.getSelectedItem().toString()));
                    p=new code.Partie(n,j,k,co,2,c);
                    new PlateauJeuLvl2(p).setVisible(true);this.dispose();
                    break;
                
           case 6: co.add(creationCode(jc1.getSelectedItem().toString()));
                    co.add(creationCode(jc2.getSelectedItem().toString()));
                    co.add(creationCode(jc3.getSelectedItem().toString()));
                    co.add(creationCode(jc4.getSelectedItem().toString()));
                    co.add(creationCode(jc5.getSelectedItem().toString()));
                    co.add(creationCode(jc6.getSelectedItem().toString()));
                    p=new code.Partie(n,j,k,co,2,c);
                    new PlateauJeu(p).setVisible(true);this.dispose();
                    break;
        }
    }//GEN-LAST:event_btnValiderActionPerformed

     public code.Couleur creationCode(String s){
        switch (s) {
            case "NOIR": return code.Couleur.NOIRE;
            case "BLEU": return code.Couleur.BLEUE;
            case "BLANC": return code.Couleur.BLANC;
            case "ROSE": return code.Couleur.ROSE;
            case "ORANGE": return code.Couleur.ORANGE;
            case "ROUGE": return code.Couleur.ROUGE;
            case "VIOLET": return code.Couleur.VIOLETTE;
            case "JAUNE": return code.Couleur.JAUNE;
            case "MARRON": return code.Couleur.MARRON;
        }
        return null;
    }
    
    public void remplirCombo(JComboBox j){
  String[] facile={"BLANC","BLEU","ROSE","ORANGE","ROUGE","NOIR"};
  String[] moyen={"BLANC","BLEU","ROSE","ORANGE","ROUGE","NOIR","VIOLET","VERT"};
  String[] difficile={"BLANC","BLEU","ROSE","ORANGE","ROUGE","NOIR","VIOLET","VERT","MARRON","JAUNE"};
  switch(n){
      case 4: for(int i=0;i<facile.length;i++){j.addItem(facile[i]);}break;
      case 5: for(int i=0;i<moyen.length;i++){j.addItem(moyen[i]);}break;
      case 6: for(int i=0;i<difficile.length;i++){j.addItem(difficile[i]);}break;   
  }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecteurCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecteurCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecteurCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecteurCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecteurCouleur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc2;
    private javax.swing.JComboBox jc3;
    private javax.swing.JComboBox jc4;
    private javax.swing.JComboBox jc5;
    private javax.swing.JComboBox jc6;
    // End of variables declaration//GEN-END:variables
}
